CREATE TABLE "barmon" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(32),
	"eng_name" varchar(32),
	"types" jsonb,
	"image_url" varchar(128),
	"level" integer,
	"exp" integer,
	"attack" integer,
	"defense" integer,
	"hp" integer,
	"speed" integer,
	"agility" integer,
	"luck" integer,
	"species" varchar(32),
	"rarity" varchar(16),
	"nature" varchar(16),
	"trait" varchar(16),
	"potential" integer,
	"star_grade" integer,
	"attribute" varchar(16)
);
