// 바몬 StateNotifierProvider 및 동적 추가/생성 로직
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/barmon.dart';
import '../utils/barmon_generator.dart';

class BarMonListNotifier extends StateNotifier<List<BarMon>> {
  BarMonListNotifier() : super(_initialBarMons);

  static final List<BarMon> _initialBarMons = [
    BarMon(
      id: '1',
      name: '은빛갈기',
      engName: 'SilverMane',
      types: [BarMonType.normal],
      imageUrl: 'assets/images/portrait/1/portrait.png',
      level: 1,
      exp: 0,
      attack: 330,
      defense: 290,
      hp: 880,
      speed: 0,
      agility: 260,
      luck: 210,
      species: '야수형',
      rarity: BarMonRarity.legendary,
      nature: '밸런스형',
      trait: '강인한',
      potential: 97,
      starGrade: 5,
      attribute: '빛',
    ),
    BarMon(
      id: '2',
      name: '심해의수호자',
      engName: 'AbyssGuardian',
      types: [BarMonType.water],
      imageUrl: 'assets/images/portrait/2/portrait.png',
      level: 1,
      exp: 0,
      attack: 210,
      defense: 360,
      hp: 790,
      speed: 0,
      agility: 110,
      luck: 85,
      species: '갑주형',
      rarity: BarMonRarity.superRare,
      nature: '방어형',
      trait: '차분한',
      potential: 85,
      starGrade: 4,
      attribute: '물',
    ),
    BarMon(
      id: '3',
      name: '불꽃발톱',
      engName: 'FlameClaw',
      types: [BarMonType.fire],
      imageUrl: 'assets/images/portrait/3/portrait.png',
      level: 1,
      exp: 0,
      attack: 290,
      defense: 160,
      hp: 470,
      speed: 0,
      agility: 230,
      luck: 105,
      species: '야수형',
      rarity: BarMonRarity.superRare,
      nature: '공격형',
      trait: '격렬한',
      potential: 78,
      starGrade: 3,
      attribute: '불',
    ),
    BarMon(
      id: '4',
      name: '구름깃털',
      engName: 'CloudFeather',
      types: [BarMonType.fairy],
      imageUrl: 'assets/images/portrait/4/portrait.png',
      level: 1,
      exp: 0,
      attack: 190,
      defense: 130,
      hp: 390,
      speed: 0,
      agility: 310,
      luck: 155,
      species: '비행형',
      rarity: BarMonRarity.rare,
      nature: '민첩형',
      trait: '경쾌한',
      potential: 65,
      starGrade: 2,
      attribute: '전기',
    ),
    BarMon(
      id: '5',
      name: '숲의정령',
      engName: 'ForestSpirit',
      types: [BarMonType.grass],
      imageUrl: 'assets/images/portrait/5/portrait.png',
      level: 1,
      exp: 0,
      attack: 170,
      defense: 240,
      hp: 620,
      speed: 0,
      agility: 95,
      luck: 75,
      species: '식물형',
      rarity: BarMonRarity.superRare,
      nature: '체력형',
      trait: '평온한',
      potential: 72,
      starGrade: 3,
      attribute: '땅',
    ),
    BarMon(
      id: '6',
      name: '별똥불',
      engName: 'Starfall',
      types: [BarMonType.psychic],
      imageUrl: 'assets/images/portrait/6/portrait.png',
      level: 1,
      exp: 0,
      attack: 280,
      defense: 190,
      hp: 560,
      speed: 0,
      agility: 210,
      luck: 200,
      species: '정령형',
      rarity: BarMonRarity.superRare,
      nature: '행운형',
      trait: '예측불가',
      potential: 82,
      starGrade: 4,
      attribute: '불',
    ),
    BarMon(
      id: '7',
      name: '황혼의눈',
      engName: 'TwilightEye',
      types: [BarMonType.dark],
      imageUrl: 'assets/images/portrait/7/portrait.png',
      level: 1,
      exp: 0,
      attack: 310,
      defense: 310,
      hp: 820,
      speed: 0,
      agility: 290,
      luck: 260,
      species: '환상형',
      rarity: BarMonRarity.legendary,
      nature: '밸런스형',
      trait: '신비한',
      potential: 99,
      starGrade: 5,
      attribute: '빛',
    ),
    BarMon(
      id: '8',
      name: '바위방패',
      engName: 'RockShield',
      types: [BarMonType.rock],
      imageUrl: 'assets/images/portrait/8/portrait.png',
      level: 1,
      exp: 0,
      attack: 160,
      defense: 290,
      hp: 590,
      speed: 0,
      agility: 105,
      luck: 65,
      species: '갑주형',
      rarity: BarMonRarity.superRare,
      nature: '방어형',
      trait: '굳건한',
      potential: 68,
      starGrade: 3,
      attribute: '땅',
    ),
    BarMon(
      id: '9',
      name: '그림자춤꾼',
      engName: 'ShadowDancer',
      types: [BarMonType.dark],
      imageUrl: 'assets/images/portrait/9/portrait.png',
      level: 1,
      exp: 0,
      attack: 210,
      defense: 110,
      hp: 360,
      speed: 0,
      agility: 290,
      luck: 125,
      species: '야수형',
      rarity: BarMonRarity.rare,
      nature: '민첩형',
      trait: '은밀한',
      potential: 57,
      starGrade: 2,
      attribute: '어둠',
    ),
    BarMon(
      id: '10',
      name: '코드제로',
      engName: 'CodeZero',
      types: [BarMonType.data],
      imageUrl: 'assets/images/portrait/10/portrait.png',
      level: 1,
      exp: 0,
      attack: 260,
      defense: 270,
      hp: 630,
      speed: 0,
      agility: 200,
      luck: 175,
      species: '인공형',
      rarity: BarMonRarity.superRare,
      nature: '공격형',
      trait: '정교한',
      potential: 92,
      starGrade: 4,
      attribute: '철',
    ),
    BarMon(
      id: '11',
      name: '이슬풀',
      engName: 'DewLeaf',
      types: [BarMonType.grass],
      imageUrl: 'assets/images/portrait/11/portrait.png',
      level: 1,
      exp: 0,
      attack: 85,
      defense: 160,
      hp: 290,
      speed: 0,
      agility: 55,
      luck: 45,
      species: '식물형',
      rarity: BarMonRarity.normal,
      nature: '체력형',
      trait: '온화한',
      potential: 42,
      starGrade: 1,
      attribute: '땅',
    ),
    BarMon(
      id: '12',
      name: '얼음심장',
      engName: 'IceHeart',
      types: [BarMonType.ice],
      imageUrl: 'assets/images/portrait/12/portrait.png',
      level: 1,
      exp: 0,
      attack: 200,
      defense: 140,
      hp: 410,
      speed: 0,
      agility: 170,
      luck: 105,
      species: '정령형',
      rarity: BarMonRarity.rare,
      nature: '방어형',
      trait: '냉철한',
      potential: 60,
      starGrade: 2,
      attribute: '얼음',
    ),
    BarMon(
      id: '13',
      name: '미지의존재',
      engName: 'UnknownBeing',
      types: [BarMonType.bug],
      imageUrl: 'assets/images/portrait/13/portrait.png',
      level: 1,
      exp: 0,
      attack: 250,
      defense: 250,
      hp: 610,
      speed: 0,
      agility: 250,
      luck: 250,
      species: '돌연변이형',
      rarity: BarMonRarity.superRare,
      nature: '밸런스형',
      trait: '변덕스러운',
      potential: 87,
      starGrade: 4,
      attribute: '무속성',
    ),
    BarMon(
      id: '14',
      name: '폭풍까마귀',
      engName: 'StormRaven',
      types: [BarMonType.bug],
      imageUrl: 'assets/images/portrait/14/portrait.png',
      level: 1,
      exp: 0,
      attack: 210,
      defense: 140,
      hp: 430,
      speed: 0,
      agility: 270,
      luck: 125,
      species: '비행형',
      rarity: BarMonRarity.superRare,
      nature: '공격형',
      trait: '맹렬한',
      potential: 75,
      starGrade: 3,
      attribute: '전기',
    ),
    BarMon(
      id: '15',
      name: '대지거인',
      engName: 'EarthGiant',
      types: [BarMonType.ground],
      imageUrl: 'assets/images/portrait/15/portrait.png',
      level: 1,
      exp: 0,
      attack: 260,
      defense: 410,
      hp: 920,
      speed: 0,
      agility: 105,
      luck: 95,
      species: '갑주형',
      rarity: BarMonRarity.legendary,
      nature: '방어형',
      trait: '불굴의',
      potential: 94,
      starGrade: 6,
      attribute: '땅',
    ),
    BarMon(
      id: '16',
      name: '꿈의조각',
      engName: 'DreamShard',
      types: [BarMonType.psychic],
      imageUrl: 'assets/images/portrait/16/portrait.png',
      level: 1,
      exp: 0,
      attack: 190,
      defense: 190,
      hp: 510,
      speed: 0,
      agility: 160,
      luck: 260,
      species: '환상형',
      rarity: BarMonRarity.superRare,
      nature: '행운형',
      trait: '신비한',
      potential: 80,
      starGrade: 3,
      attribute: '빛',
    ),
    BarMon(
      id: '17',
      name: '강철핵',
      engName: 'SteelCore',
      types: [BarMonType.steel],
      imageUrl: 'assets/images/portrait/17/portrait.png',
      level: 1,
      exp: 0,
      attack: 190,
      defense: 230,
      hp: 490,
      speed: 0,
      agility: 85,
      luck: 55,
      species: '인공형',
      rarity: BarMonRarity.rare,
      nature: '방어형',
      trait: '육중한',
      potential: 63,
      starGrade: 2,
      attribute: '철',
    ),
    BarMon(
      id: '18',
      name: '번개발톱',
      engName: 'ThunderFang',
      types: [BarMonType.electric],
      imageUrl: 'assets/images/portrait/18/portrait.png',
      level: 1,
      exp: 0,
      attack: 290,
      defense: 210,
      hp: 610,
      speed: 0,
      agility: 300,
      luck: 160,
      species: '야수형',
      rarity: BarMonRarity.superRare,
      nature: '민첩형',
      trait: '날렵한',
      potential: 89,
      starGrade: 4,
      attribute: '전기',
    ),
    BarMon(
      id: '19',
      name: '별무리',
      engName: 'StarCluster',
      types: [BarMonType.psychic],
      imageUrl: 'assets/images/portrait/19/portrait.png',
      level: 1,
      exp: 0,
      attack: 155,
      defense: 105,
      hp: 360,
      speed: 0,
      agility: 105,
      luck: 210,
      species: '돌연변이형',
      rarity: BarMonRarity.rare,
      nature: '행운형',
      trait: '예측불가',
      potential: 52,
      starGrade: 2,
      attribute: '무속성',
    ),
    BarMon(
      id: '20',
      name: '천상용',
      engName: 'CelestialDragon',
      types: [BarMonType.dragon],
      imageUrl: 'assets/images/portrait/20/portrait.png',
      level: 1,
      exp: 0,
      attack: 390,
      defense: 310,
      hp: 970,
      speed: 0,
      agility: 290,
      luck: 230,
      species: '용형',
      rarity: BarMonRarity.legendary,
      nature: '밸런스형',
      trait: '고귀한',
      potential: 100,
      starGrade: 6,
      attribute: '빛',
    ),
  ];

  void addBarMonFromScan({
    required String barcode,
    required String accountId,
    bool isBusiness = false,
    String? businessPrefix,
  }) {
    final newBarMon = generateBarMon(
      barcode: barcode,
      accountId: accountId,
      isBusiness: isBusiness,
      businessPrefix: businessPrefix,
    );
    // 중복 방지(동일 id 존재 시 추가 안함)
    if (!state.any((b) => b.id == newBarMon.id)) {
      state = [...state, newBarMon];
    }
  }
}

final barMonListProvider = StateNotifierProvider<BarMonListNotifier, List<BarMon>>(
  (ref) => BarMonListNotifier(),
);
